-- tambahin timezone default now
-- periksa created_at kalo belom ada
-- tambahin table prefix counters
-- table pivot many to many crew dan crew_skills

CREATE TABLE "profiles" (
  user_uuid uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  "role" text NOT NULL DEFAULT 'user',
  "avatar_url" text,
  "full_name" text NOT NULL,
  "phone" varchar UNIQUE ,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "location_tags" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "name" text UNIQUE NOT NULL,
  "created_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "location_tag" (
  "location_tag_id" integer NOT NULL,
  "location_id" integer NOT NULL,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  PRIMARY KEY ("location_tag_id", "location_id")
);

CREATE TABLE "location_images" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "location_id" integer NOT NULL,
  "url" text NOT NULL,
  "position" integer NOT NULL DEFAULT 0
);

CREATE TABLE "locations" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "uuid" uuid UNIQUE NOT NULL,
  "code" text UNIQUE NOT NULL,
  "name" text NOT NULL,
  "description" text,
  "city" text,
  "price" integer NOT NULL DEFAULT 0,
  "area" integer,
  "pax" integer,
  "is_available" boolean NOT NULL DEFAULT true,
  "updated_at" timestamptz NOT NULL DEFAULT (now()),
  "rating" integer
);

CREATE TABLE "crews" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "uuid" uuid UNIQUE NOT NULL,
  "code" text UNIQUE NOT NULL,
  "name" text NOT NULL,
  "description" text,
  "price" integer NOT NULL DEFAULT 0,
  "is_available" boolean NOT NULL DEFAULT true,
  "updated_at" timestamptz NOT NULL DEFAULT (now()),
  "created_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "rentals" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "uuid" uuid UNIQUE NOT NULL,
  "code" text UNIQUE NOT NULL,
  "name" text NOT NULL,
  "description" text,
  "price" integer NOT NULL DEFAULT 0,
  "specifications" jsonb,
  "is_available" boolean NOT NULL DEFAULT true,
  "updated_at" timestamptz NOT NULL DEFAULT (now()),
  "created_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "expendables" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "uuid" uuid UNIQUE NOT NULL,
  "code" text UNIQUE NOT NULL,
  "name" text NOT NULL,
  "description" text,
  "price" integer NOT NULL DEFAULT 0,
  "is_available" boolean NOT NULL DEFAULT true,
  "updated_at" timestamptz NOT NULL DEFAULT (now()),
  "created_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "food_and_beverage" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "uuid" uuid UNIQUE NOT NULL,
  "code" text UNIQUE NOT NULL,
  "name" text NOT NULL,
  "description" text,
  "price" integer NOT NULL DEFAULT 0,
  "images" text[],
  "is_available" boolean NOT NULL DEFAULT true,
  "updated_at" timestamptz NOT NULL DEFAULT (now()),
  "created_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "food_and_beverage_tags" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "name" text UNIQUE NOT NULL,
  "created_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "food_and_beverage_tag" (
  "food_and_beverage_tag_id" integer NOT NULL,
  "food_and_beverage_id" integer NOT NULL,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  PRIMARY KEY ("food_and_beverage_tag_id", "food_and_beverage_id")
);

CREATE TABLE "location_embeddings" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "location_id" integer NOT NULL,
  "content" jsonb NOT NULL,
  "embedding" public.vector NOT NULL,
  "created_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "location_reviews" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "uuid" uuid UNIQUE NOT NULL,
  "user_uuid" uuid NOT NULL,
  "location_id" integer NOT NULL,
  "rating" integer NOT NULL,
  "comment" text,
  "order_id" integer NOT NULL,
  "created_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "promo_codes" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "code" text UNIQUE NOT NULL,
  "discount_type" text NOT NULL,
  "discount_value" integer NOT NULL DEFAULT 0,
  "max_usage" integer,
  "usage_count" integer NOT NULL DEFAULT 0,
  "max_usage_per_user" integer,
  "min_order_amount" integer NOT NULL DEFAULT 0,
  "starts_at" timestamptz,
  "expires_at" timestamptz,
  "is_active" boolean NOT NULL DEFAULT true,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "bundles" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "uuid" uuid UNIQUE NOT NULL,
  "name" text NOT NULL,
  "description" text,
  "is_active" boolean NOT NULL DEFAULT true,
  "base_price" integer NOT NULL DEFAULT 0,
  "discount_type" text,
  "discount_value" integer NOT NULL DEFAULT 0,
  "final_price" integer NOT NULL DEFAULT 0,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "bundle_crews" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "uuid" uuid UNIQUE NOT NULL,
  "bundle_id" integer NOT NULL,
  "crew_id" integer NOT NULL,
  "quantity" integer NOT NULL DEFAULT 1,
  "notes" text,
  "created_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "bundle_rentals" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "uuid" uuid UNIQUE NOT NULL,
  "bundle_id" integer NOT NULL,
  "rental_id" integer NOT NULL,
  "quantity" integer NOT NULL DEFAULT 1,
  "notes" text,
  "created_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "bundle_food_and_beverages" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "uuid" uuid UNIQUE NOT NULL,
  "bundle_id" integer NOT NULL,
  "food_and_beverage_id" integer NOT NULL,
  "quantity" integer NOT NULL DEFAULT 1,
  "notes" text,
  "created_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "bundle_expendables" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "uuid" uuid UNIQUE NOT NULL,
  "bundle_id" integer NOT NULL,
  "expendable_id" integer NOT NULL,
  "quantity" integer NOT NULL DEFAULT 1,
  "notes" text,
  "created_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "crew_skills" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "name" text NOT NULL,
  "description" text,
  "created_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "orders" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "uuid" uuid UNIQUE NOT NULL,
  "code" text UNIQUE NOT NULL,
  "user_uuid" uuid NOT NULL,
  "purpose" text NOT NULL,
  "shooting_address" text NOT NULL,
  "payment_status" text NOT NULL DEFAULT 'pending',
  "subtotal_amount" integer NOT NULL DEFAULT 0,
  "bundle_discount_amount" integer NOT NULL DEFAULT 0,
  "promo_discount_amount" integer NOT NULL DEFAULT 0,
  "total_discount_amount" integer NOT NULL DEFAULT 0,
  "grand_total_amount" integer NOT NULL DEFAULT 0,
  "promo_code_id" integer,
  "promo_code_snapshot" text,
  "promo_discount_type_snapshot" text,
  "promo_discount_value_snapshot" integer,
  "midtrans_token" text,
  "midtrans_expired_at" timestamptz,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "order_items" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "uuid" uuid UNIQUE NOT NULL,
  "order_id" integer NOT NULL,
  "item_type" text NOT NULL,
  "item_id" integer NOT NULL,
  "item_name_snapshot" text,
  "quantity" integer NOT NULL DEFAULT 1,
  "unit_price_snapshot" integer NOT NULL DEFAULT 0,
  "line_total" integer NOT NULL DEFAULT 0,
  "is_from_bundle" boolean NOT NULL DEFAULT false,
  "bundle_id" integer,
  "booking_start" date,
  "booking_end" date,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "crew_images" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "crew_id" integer NOT NULL,
  "url" text NOT NULL,
  "position" integer NOT NULL DEFAULT 0
);

CREATE TABLE "expendable_images" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "expendable_id" integer NOT NULL,
  "url" text NOT NULL,
  "position" integer NOT NULL DEFAULT 0
);

CREATE TABLE "food_and_beverage_images" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "food_and_beverage_id" integer NOT NULL,
  "url" text NOT NULL,
  "position" integer NOT NULL DEFAULT 0
);

CREATE TABLE "rental_images" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "rental_id" integer NOT NULL,
  "url" text NOT NULL,
  "position" integer NOT NULL DEFAULT 0
);

CREATE TABLE "item_categories" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "name" text,
  "short_code" text,
  "created_at" timestamptz
);

CREATE TABLE "item_sub_categories" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "name" text,
  "short_code" text,
  "created_at" timestamptz
);

CREATE TABLE "bundle_types" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "name" text,
  "short_code" text,
  "created_at" timestamptz
);

CREATE TABLE "bundle_categories" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "name" text,
  "short_code" text,
  "created_at" timestamptz
);

CREATE TABLE "location_item_category" (
  "location_id" integer NOT NULL,
  "item_category_id" integer NOT NULL,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  PRIMARY KEY ("location_id", "item_category_id")
);

CREATE TABLE "rental_item_category" (
  "rental_id" integer NOT NULL,
  "item_category_id" integer NOT NULL,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  PRIMARY KEY ("rental_id", "item_category_id")
);

CREATE TABLE "expendable_item_category" (
  "expendable_id" integer NOT NULL,
  "item_category_id" integer NOT NULL,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  PRIMARY KEY ("expendable_id", "item_category_id")
);

CREATE TABLE "food_and_beverage_item_category" (
  "food_and_beverage_id" integer NOT NULL,
  "item_category_id" integer NOT NULL,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  PRIMARY KEY ("food_and_beverage_id", "item_category_id")
);

CREATE TABLE "crew_item_category" (
  "crew_id" integer NOT NULL,
  "item_category_id" integer NOT NULL,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  PRIMARY KEY ("crew_id", "item_category_id")
);

CREATE TABLE "location_item_sub_category" (
  "location_id" integer NOT NULL,
  "item_sub_category_id" integer NOT NULL,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  PRIMARY KEY ("location_id", "item_sub_category_id")
);

CREATE TABLE "rental_item_sub_category" (
  "rental_id" integer NOT NULL,
  "item_sub_category_id" integer NOT NULL,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  PRIMARY KEY ("rental_id", "item_sub_category_id")
);

CREATE TABLE "expendable_item_sub_category" (
  "expendable_id" integer NOT NULL,
  "item_sub_category_id" integer NOT NULL,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  PRIMARY KEY ("expendable_id", "item_sub_category_id")
);

CREATE TABLE "food_and_beverage_item_sub_category" (
  "food_and_beverage_id" integer NOT NULL,
  "item_sub_category_id" integer NOT NULL,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  PRIMARY KEY ("food_and_beverage_id", "item_sub_category_id")
);

CREATE TABLE "crew_item_sub_category" (
  "crew_id" integer NOT NULL,
  "item_sub_category_id" integer NOT NULL,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  PRIMARY KEY ("crew_id", "item_sub_category_id")
);

CREATE TABLE "bundle_type" (
  "bundle_id" integer NOT NULL,
  "bundle_type_id" integer NOT NULL,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  PRIMARY KEY ("bundle_id", "bundle_type_id")
);

CREATE TABLE "bundle_category" (
  "bundle_id" integer NOT NULL,
  "bundle_category_id" integer NOT NULL,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  PRIMARY KEY ("bundle_id", "bundle_category_id")
);

CREATE INDEX ON "profiles" ("role");

CREATE INDEX ON "profiles" ("phone");

CREATE INDEX ON "profiles" ("created_at");

CREATE INDEX ON "location_tags" ("name");

CREATE INDEX ON "location_tag" ("location_tag_id");

CREATE INDEX ON "location_tag" ("location_id");

CREATE UNIQUE INDEX ON "location_tag" ("location_tag_id", "location_id");

CREATE INDEX ON "location_images" ("location_id");

CREATE INDEX ON "location_images" ("location_id", "position");

CREATE INDEX ON "locations" ("uuid");

CREATE INDEX ON "locations" ("code");

CREATE INDEX ON "locations" ("name");

CREATE INDEX ON "locations" ("city");

CREATE INDEX ON "locations" ("price");

CREATE INDEX ON "crews" ("uuid");

CREATE INDEX ON "crews" ("code");

CREATE INDEX ON "crews" ("name");

CREATE INDEX ON "crews" ("is_available");

CREATE INDEX ON "crews" ("price");

CREATE INDEX ON "rentals" ("uuid");

CREATE INDEX ON "rentals" ("code");

CREATE INDEX ON "rentals" ("name");

CREATE INDEX ON "rentals" ("is_available");

CREATE INDEX ON "rentals" ("price");

CREATE INDEX ON "expendables" ("uuid");

CREATE INDEX ON "expendables" ("code");

CREATE INDEX ON "expendables" ("name");

CREATE INDEX ON "expendables" ("is_available");

CREATE INDEX ON "expendables" ("price");

CREATE INDEX ON "food_and_beverage" ("uuid");

CREATE INDEX ON "food_and_beverage" ("code");

CREATE INDEX ON "food_and_beverage" ("name");

CREATE INDEX ON "food_and_beverage" ("is_available");

CREATE INDEX ON "food_and_beverage" ("price");

CREATE INDEX ON "food_and_beverage_tags" ("name");

CREATE INDEX ON "food_and_beverage_tag" ("food_and_beverage_tag_id");

CREATE INDEX ON "food_and_beverage_tag" ("food_and_beverage_id");

CREATE UNIQUE INDEX ON "food_and_beverage_tag" ("food_and_beverage_tag_id", "food_and_beverage_id");

CREATE INDEX ON "location_embeddings" ("location_id");

CREATE INDEX ON "location_embeddings" ("created_at");

CREATE INDEX ON "location_reviews" ("user_uuid");

CREATE INDEX ON "location_reviews" ("location_id");

CREATE INDEX ON "location_reviews" ("order_id");

CREATE INDEX ON "location_reviews" ("rating");

CREATE INDEX ON "promo_codes" ("code");

CREATE INDEX ON "promo_codes" ("is_active");

CREATE INDEX ON "promo_codes" ("starts_at");

CREATE INDEX ON "promo_codes" ("expires_at");

CREATE INDEX ON "bundles" ("uuid");

CREATE INDEX ON "bundles" ("name");

CREATE INDEX ON "bundles" ("is_active");

CREATE INDEX ON "bundles" ("final_price");

CREATE INDEX ON "bundle_crews" ("bundle_id");

CREATE INDEX ON "bundle_crews" ("crew_id");

CREATE UNIQUE INDEX ON "bundle_crews" ("bundle_id", "crew_id");

CREATE INDEX ON "bundle_rentals" ("bundle_id");

CREATE INDEX ON "bundle_rentals" ("rental_id");

CREATE UNIQUE INDEX ON "bundle_rentals" ("bundle_id", "rental_id");

CREATE INDEX ON "bundle_food_and_beverages" ("bundle_id");

CREATE INDEX ON "bundle_food_and_beverages" ("food_and_beverage_id");

CREATE UNIQUE INDEX ON "bundle_food_and_beverages" ("bundle_id", "food_and_beverage_id");

CREATE INDEX ON "bundle_expendables" ("bundle_id");

CREATE INDEX ON "bundle_expendables" ("expendable_id");

CREATE UNIQUE INDEX ON "bundle_expendables" ("bundle_id", "expendable_id");

CREATE INDEX ON "crew_skills" ("crew_id");

CREATE INDEX ON "crew_skills" ("name");

CREATE INDEX ON "crew_skills" ("crew_id", "name");

CREATE INDEX ON "orders" ("uuid");

CREATE INDEX ON "orders" ("code");

CREATE INDEX ON "orders" ("user_uuid");

CREATE INDEX ON "orders" ("payment_status");

CREATE INDEX ON "orders" ("created_at");

CREATE INDEX ON "orders" ("promo_code_id");

CREATE INDEX ON "order_items" ("order_id");

CREATE INDEX ON "order_items" ("item_type", "item_id");

CREATE INDEX ON "order_items" ("bundle_id");

CREATE INDEX ON "order_items" ("is_from_bundle");

CREATE INDEX ON "order_items" ("booking_start", "booking_end");

CREATE INDEX ON "crew_images" ("crew_id");

CREATE INDEX ON "crew_images" ("crew_id", "position");

CREATE INDEX ON "expendable_images" ("expendable_id");

CREATE INDEX ON "expendable_images" ("expendable_id", "position");

CREATE INDEX ON "food_and_beverage_images" ("food_and_beverage_id");

CREATE INDEX ON "food_and_beverage_images" ("food_and_beverage_id", "position");

CREATE INDEX ON "rental_images" ("rental_id");

CREATE INDEX ON "rental_images" ("rental_id", "position");

CREATE INDEX ON "location_item_category" ("item_category_id");

CREATE UNIQUE INDEX ON "location_item_category" ("location_id", "item_category_id");

CREATE INDEX ON "rental_item_category" ("item_category_id");

CREATE UNIQUE INDEX ON "rental_item_category" ("rental_id", "item_category_id");

CREATE INDEX ON "expendable_item_category" ("item_category_id");

CREATE UNIQUE INDEX ON "expendable_item_category" ("expendable_id", "item_category_id");

CREATE INDEX ON "food_and_beverage_item_category" ("item_category_id");

CREATE UNIQUE INDEX ON "food_and_beverage_item_category" ("food_and_beverage_id", "item_category_id");

CREATE INDEX ON "crew_item_category" ("item_category_id");

CREATE UNIQUE INDEX ON "crew_item_category" ("crew_id", "item_category_id");

CREATE INDEX ON "location_item_sub_category" ("item_sub_category_id");

CREATE UNIQUE INDEX ON "location_item_sub_category" ("location_id", "item_sub_category_id");

CREATE INDEX ON "rental_item_sub_category" ("item_sub_category_id");

CREATE UNIQUE INDEX ON "rental_item_sub_category" ("rental_id", "item_sub_category_id");

CREATE INDEX ON "expendable_item_sub_category" ("item_sub_category_id");

CREATE UNIQUE INDEX ON "expendable_item_sub_category" ("expendable_id", "item_sub_category_id");

CREATE INDEX ON "food_and_beverage_item_sub_category" ("item_sub_category_id");

CREATE UNIQUE INDEX ON "food_and_beverage_item_sub_category" ("food_and_beverage_id", "item_sub_category_id");

CREATE INDEX ON "crew_item_sub_category" ("item_sub_category_id");

CREATE UNIQUE INDEX ON "crew_item_sub_category" ("crew_id", "item_sub_category_id");

CREATE INDEX ON "bundle_bundle_types" ("bundle_type_id");

CREATE UNIQUE INDEX ON "bundle_bundle_types" ("bundle_id", "bundle_type_id");

CREATE INDEX ON "bundle_bundle_categories" ("bundle_category_id");

CREATE UNIQUE INDEX ON "bundle_bundle_categories" ("bundle_id", "bundle_category_id");

COMMENT ON TABLE "profiles" IS 'Menyimpan informasi detail user; terhubung ke auth.users via uuid';

COMMENT ON COLUMN "profiles"."user_uuid" IS 'Primary key, reference ke auth.users.id';

COMMENT ON COLUMN "profiles"."role" IS 'Role user: user/admin';

COMMENT ON COLUMN "profiles"."avatar_url" IS 'URL avatar user';

COMMENT ON COLUMN "profiles"."full_name" IS 'Nama lengkap user';

COMMENT ON COLUMN "profiles"."phone" IS 'Nomor telepon user';

COMMENT ON COLUMN "profiles"."created_at" IS 'Waktu dibuat';

COMMENT ON COLUMN "profiles"."updated_at" IS 'Waktu diperbarui';

COMMENT ON TABLE "location_tags" IS 'Master tag untuk location';

COMMENT ON COLUMN "location_tags"."id" IS 'Primary key tag';

COMMENT ON COLUMN "location_tags"."name" IS 'Nama tag location';

COMMENT ON COLUMN "location_tags"."created_at" IS 'Waktu dibuat';

COMMENT ON TABLE "location_tag" IS 'Table pivot many-to-many antara location_tags dan locations';

COMMENT ON COLUMN "location_tag"."location_tag_id" IS 'FK ke location_tags.id';

COMMENT ON COLUMN "location_tag"."location_id" IS 'FK ke locations.id';

COMMENT ON COLUMN "location_tag"."created_at" IS 'Waktu asosiasi dibuat';

COMMENT ON TABLE "location_images" IS 'Menampung gambar location';

COMMENT ON COLUMN "location_images"."id" IS 'Primary key gambar';

COMMENT ON COLUMN "location_images"."location_id" IS 'FK ke locations.id';

COMMENT ON COLUMN "location_images"."url" IS 'URL gambar';

COMMENT ON COLUMN "location_images"."position" IS 'Urutan gambar';

COMMENT ON TABLE "locations" IS 'Master data shooting location';

COMMENT ON COLUMN "locations"."id" IS 'Primary key location';

COMMENT ON COLUMN "locations"."uuid" IS 'ID publik location';

COMMENT ON COLUMN "locations"."code" IS 'Kode location';

COMMENT ON COLUMN "locations"."name" IS 'Nama location';

COMMENT ON COLUMN "locations"."description" IS 'Deskripsi location';

COMMENT ON COLUMN "locations"."city" IS 'Kota location';

COMMENT ON COLUMN "locations"."price" IS 'Harga dasar location';

COMMENT ON COLUMN "locations"."area" IS 'Luas area';

COMMENT ON COLUMN "locations"."pax" IS 'Kapasitas orang';

COMMENT ON COLUMN "locations"."is_available" IS 'Status ketersediaan';

COMMENT ON COLUMN "locations"."updated_at" IS 'Waktu diperbarui';

COMMENT ON COLUMN "locations"."rating" IS 'Rating agregat';

COMMENT ON TABLE "crews" IS 'Master data kru produksi';

COMMENT ON COLUMN "crews"."id" IS 'Primary key crew';

COMMENT ON COLUMN "crews"."uuid" IS 'ID publik crew';

COMMENT ON COLUMN "crews"."code" IS 'Kode crew';

COMMENT ON COLUMN "crews"."name" IS 'Nama crew';

COMMENT ON COLUMN "crews"."description" IS 'Deskripsi crew';

COMMENT ON COLUMN "crews"."price" IS 'Harga per crew';

COMMENT ON COLUMN "crews"."skills" IS 'Daftar skill crew';

COMMENT ON COLUMN "crews"."images" IS 'Legacy kolom gambar; pertimbangkan pakai crew_images';

COMMENT ON COLUMN "crews"."is_available" IS 'Status ketersediaan';

COMMENT ON COLUMN "crews"."updated_at" IS 'Waktu diperbarui';

COMMENT ON COLUMN "crews"."created_at" IS 'Waktu dibuat';

COMMENT ON TABLE "rentals" IS 'Master data item rental/peralatan';

COMMENT ON COLUMN "rentals"."id" IS 'Primary key rental';

COMMENT ON COLUMN "rentals"."uuid" IS 'ID publik rental';

COMMENT ON COLUMN "rentals"."code" IS 'Kode rental';

COMMENT ON COLUMN "rentals"."name" IS 'Nama item rental';

COMMENT ON COLUMN "rentals"."description" IS 'Deskripsi rental';

COMMENT ON COLUMN "rentals"."price" IS 'Harga rental';

COMMENT ON COLUMN "rentals"."specs" IS 'Spesifikasi item';

COMMENT ON COLUMN "rentals"."images" IS 'Legacy kolom gambar; pertimbangkan pakai rental_images';

COMMENT ON COLUMN "rentals"."is_available" IS 'Status ketersediaan';

COMMENT ON COLUMN "rentals"."updated_at" IS 'Waktu diperbarui';

COMMENT ON COLUMN "rentals"."created_at" IS 'Waktu dibuat';

COMMENT ON TABLE "expendables" IS 'Master data expendables/habis pakai';

COMMENT ON COLUMN "expendables"."id" IS 'Primary key expendable';

COMMENT ON COLUMN "expendables"."uuid" IS 'ID publik expendable';

COMMENT ON COLUMN "expendables"."code" IS 'Kode expendable';

COMMENT ON COLUMN "expendables"."name" IS 'Nama expendable';

COMMENT ON COLUMN "expendables"."description" IS 'Deskripsi expendable';

COMMENT ON COLUMN "expendables"."price" IS 'Harga expendable';

COMMENT ON COLUMN "expendables"."images" IS 'Legacy kolom gambar; pertimbangkan pakai expendable_images';

COMMENT ON COLUMN "expendables"."is_available" IS 'Status ketersediaan';

COMMENT ON COLUMN "expendables"."updated_at" IS 'Waktu diperbarui';

COMMENT ON COLUMN "expendables"."created_at" IS 'Waktu dibuat';

COMMENT ON TABLE "food_and_beverage" IS 'Master data food and beverage';

COMMENT ON COLUMN "food_and_beverage"."id" IS 'Primary key F&B';

COMMENT ON COLUMN "food_and_beverage"."uuid" IS 'ID publik F&B';

COMMENT ON COLUMN "food_and_beverage"."code" IS 'Kode F&B';

COMMENT ON COLUMN "food_and_beverage"."name" IS 'Nama F&B';

COMMENT ON COLUMN "food_and_beverage"."description" IS 'Deskripsi F&B';

COMMENT ON COLUMN "food_and_beverage"."price" IS 'Harga F&B';

COMMENT ON COLUMN "food_and_beverage"."images" IS 'Legacy kolom gambar; pertimbangkan pakai food_and_beverage_images';

COMMENT ON COLUMN "food_and_beverage"."is_available" IS 'Status ketersediaan';

COMMENT ON COLUMN "food_and_beverage"."updated_at" IS 'Waktu diperbarui';

COMMENT ON COLUMN "food_and_beverage"."created_at" IS 'Waktu dibuat';

COMMENT ON TABLE "food_and_beverage_tags" IS 'Master tag untuk F&B';

COMMENT ON COLUMN "food_and_beverage_tags"."id" IS 'Primary key tag F&B';

COMMENT ON COLUMN "food_and_beverage_tags"."name" IS 'Nama tag F&B';

COMMENT ON COLUMN "food_and_beverage_tags"."created_at" IS 'Waktu dibuat';

COMMENT ON TABLE "food_and_beverage_tag" IS 'Pivot many-to-many antara food_and_beverage_tags dan food_and_beverage';

COMMENT ON COLUMN "food_and_beverage_tag"."food_and_beverage_tag_id" IS 'FK ke food_and_beverage_tags.id';

COMMENT ON COLUMN "food_and_beverage_tag"."food_and_beverage_id" IS 'FK ke food_and_beverage.id';

COMMENT ON COLUMN "food_and_beverage_tag"."created_at" IS 'Waktu asosiasi dibuat';

COMMENT ON TABLE "location_embeddings" IS 'Penyimpanan embedding vector untuk semantic search location';

COMMENT ON COLUMN "location_embeddings"."id" IS 'Primary key embedding';

COMMENT ON COLUMN "location_embeddings"."location_id" IS 'FK ke locations.id';

COMMENT ON COLUMN "location_embeddings"."content" IS 'Payload konten yang di-embed';

COMMENT ON COLUMN "location_embeddings"."embedding" IS 'Vector embedding';

COMMENT ON COLUMN "location_embeddings"."created_at" IS 'Waktu dibuat';

COMMENT ON TABLE "location_reviews" IS 'Review user untuk location, terkait transaksi order';

COMMENT ON COLUMN "location_reviews"."id" IS 'Primary key review';

COMMENT ON COLUMN "location_reviews"."uuid" IS 'ID publik review';

COMMENT ON COLUMN "location_reviews"."user_uuid" IS 'FK ke profiles.uuid';

COMMENT ON COLUMN "location_reviews"."location_id" IS 'FK ke locations.id';

COMMENT ON COLUMN "location_reviews"."rating" IS 'Nilai rating';

COMMENT ON COLUMN "location_reviews"."comment" IS 'Komentar review';

COMMENT ON COLUMN "location_reviews"."order_id" IS 'FK ke orders.id';

COMMENT ON COLUMN "location_reviews"."created_at" IS 'Waktu dibuat';

COMMENT ON TABLE "promo_codes" IS 'Master promo code untuk potongan harga saat checkout';

COMMENT ON COLUMN "promo_codes"."id" IS 'Primary key promo';

COMMENT ON COLUMN "promo_codes"."code" IS 'Kode promo';

COMMENT ON COLUMN "promo_codes"."discount_type" IS 'Jenis diskon: percent/fixed';

COMMENT ON COLUMN "promo_codes"."discount_value" IS 'Nilai diskon';

COMMENT ON COLUMN "promo_codes"."max_usage" IS 'Maks penggunaan total';

COMMENT ON COLUMN "promo_codes"."usage_count" IS 'Jumlah penggunaan saat ini';

COMMENT ON COLUMN "promo_codes"."max_usage_per_user" IS 'Maks penggunaan per user';

COMMENT ON COLUMN "promo_codes"."min_order_amount" IS 'Minimum belanja';

COMMENT ON COLUMN "promo_codes"."starts_at" IS 'Mulai berlaku';

COMMENT ON COLUMN "promo_codes"."expires_at" IS 'Akhir berlaku';

COMMENT ON COLUMN "promo_codes"."is_active" IS 'Status aktif promo';

COMMENT ON COLUMN "promo_codes"."created_at" IS 'Waktu dibuat';

COMMENT ON COLUMN "promo_codes"."updated_at" IS 'Waktu diperbarui';

COMMENT ON TABLE "bundles" IS 'Master bundling/paketan; final_price adalah harga jual paket';

COMMENT ON COLUMN "bundles"."id" IS 'Primary key bundle';

COMMENT ON COLUMN "bundles"."uuid" IS 'ID publik bundle';

COMMENT ON COLUMN "bundles"."name" IS 'Nama bundle';

COMMENT ON COLUMN "bundles"."description" IS 'Deskripsi bundle';

COMMENT ON COLUMN "bundles"."is_active" IS 'Status aktif bundle';

COMMENT ON COLUMN "bundles"."base_price" IS 'Harga normal total item bundle';

COMMENT ON COLUMN "bundles"."discount_type" IS 'Jenis diskon bundle: percent/fixed';

COMMENT ON COLUMN "bundles"."discount_value" IS 'Nilai diskon bundle';

COMMENT ON COLUMN "bundles"."final_price" IS 'Harga akhir bundle';

COMMENT ON COLUMN "bundles"."created_at" IS 'Waktu dibuat';

COMMENT ON COLUMN "bundles"."updated_at" IS 'Waktu diperbarui';

COMMENT ON TABLE "bundle_crews" IS 'Detail crew dalam bundle';

COMMENT ON COLUMN "bundle_crews"."id" IS 'Primary key';

COMMENT ON COLUMN "bundle_crews"."uuid" IS 'ID publik baris detail';

COMMENT ON COLUMN "bundle_crews"."bundle_id" IS 'FK ke bundles.id';

COMMENT ON COLUMN "bundle_crews"."crew_id" IS 'FK ke crews.id';

COMMENT ON COLUMN "bundle_crews"."quantity" IS 'Jumlah crew di bundle';

COMMENT ON COLUMN "bundle_crews"."notes" IS 'Catatan tambahan';

COMMENT ON COLUMN "bundle_crews"."created_at" IS 'Waktu dibuat';

COMMENT ON TABLE "bundle_rentals" IS 'Detail rental dalam bundle';

COMMENT ON COLUMN "bundle_rentals"."id" IS 'Primary key';

COMMENT ON COLUMN "bundle_rentals"."uuid" IS 'ID publik baris detail';

COMMENT ON COLUMN "bundle_rentals"."bundle_id" IS 'FK ke bundles.id';

COMMENT ON COLUMN "bundle_rentals"."rental_id" IS 'FK ke rentals.id';

COMMENT ON COLUMN "bundle_rentals"."quantity" IS 'Jumlah rental di bundle';

COMMENT ON COLUMN "bundle_rentals"."notes" IS 'Catatan tambahan';

COMMENT ON COLUMN "bundle_rentals"."created_at" IS 'Waktu dibuat';

COMMENT ON TABLE "bundle_food_and_beverages" IS 'Detail food and beverage dalam bundle';

COMMENT ON COLUMN "bundle_food_and_beverages"."id" IS 'Primary key';

COMMENT ON COLUMN "bundle_food_and_beverages"."uuid" IS 'ID publik baris detail';

COMMENT ON COLUMN "bundle_food_and_beverages"."bundle_id" IS 'FK ke bundles.id';

COMMENT ON COLUMN "bundle_food_and_beverages"."food_and_beverage_id" IS 'FK ke food_and_beverage.id';

COMMENT ON COLUMN "bundle_food_and_beverages"."quantity" IS 'Jumlah F&B di bundle';

COMMENT ON COLUMN "bundle_food_and_beverages"."notes" IS 'Catatan tambahan';

COMMENT ON COLUMN "bundle_food_and_beverages"."created_at" IS 'Waktu dibuat';

COMMENT ON TABLE "bundle_expendables" IS 'Detail expendable dalam bundle';

COMMENT ON COLUMN "bundle_expendables"."id" IS 'Primary key';

COMMENT ON COLUMN "bundle_expendables"."uuid" IS 'ID publik baris detail';

COMMENT ON COLUMN "bundle_expendables"."bundle_id" IS 'FK ke bundles.id';

COMMENT ON COLUMN "bundle_expendables"."expendable_id" IS 'FK ke expendables.id';

COMMENT ON COLUMN "bundle_expendables"."quantity" IS 'Jumlah expendable di bundle';

COMMENT ON COLUMN "bundle_expendables"."notes" IS 'Catatan tambahan';

COMMENT ON COLUMN "bundle_expendables"."created_at" IS 'Waktu dibuat';

COMMENT ON TABLE "crew_skills" IS 'Master skill per crew';

COMMENT ON COLUMN "crew_skills"."id" IS 'Primary key skill';

COMMENT ON COLUMN "crew_skills"."crew_id" IS 'FK ke crews.id';

COMMENT ON COLUMN "crew_skills"."name" IS 'Nama skill';

COMMENT ON COLUMN "crew_skills"."description" IS 'Deskripsi skill; ini fungsinya apa ya ?';

COMMENT ON COLUMN "crew_skills"."created_at" IS 'Waktu dibuat';

COMMENT ON TABLE "orders" IS 'Header transaksi order';

COMMENT ON COLUMN "orders"."id" IS 'Primary key order';

COMMENT ON COLUMN "orders"."uuid" IS 'ID publik order';

COMMENT ON COLUMN "orders"."code" IS 'Kode order human-readable';

COMMENT ON COLUMN "orders"."user_uuid" IS 'FK ke profiles.uuid';

COMMENT ON COLUMN "orders"."purpose" IS 'Tujuan pemotretan';

COMMENT ON COLUMN "orders"."shooting_address" IS 'Alamat lokasi shooting';

COMMENT ON COLUMN "orders"."payment_status" IS 'Status pembayaran: pending/paid/failed/expired/canceled/refunded';

COMMENT ON COLUMN "orders"."subtotal_amount" IS 'Total sebelum diskon';

COMMENT ON COLUMN "orders"."bundle_discount_amount" IS 'Total diskon bundling';

COMMENT ON COLUMN "orders"."promo_discount_amount" IS 'Total diskon promo';

COMMENT ON COLUMN "orders"."total_discount_amount" IS 'Bundle + promo';

COMMENT ON COLUMN "orders"."grand_total_amount" IS 'Total akhir dibayar';

COMMENT ON COLUMN "orders"."promo_code_id" IS 'FK ke promo_codes.id; null jika tanpa promo';

COMMENT ON COLUMN "orders"."promo_code_snapshot" IS 'Kode promo saat checkout';

COMMENT ON COLUMN "orders"."promo_discount_type_snapshot" IS 'Snapshot jenis diskon promo: percent/fixed';

COMMENT ON COLUMN "orders"."promo_discount_value_snapshot" IS 'Snapshot nilai diskon promo';

COMMENT ON COLUMN "orders"."midtrans_token" IS 'Token transaksi dari Midtrans';

COMMENT ON COLUMN "orders"."midtrans_expired_at" IS 'Waktu token Midtrans kadaluarsa';

COMMENT ON COLUMN "orders"."created_at" IS 'Waktu dibuat';

COMMENT ON COLUMN "orders"."updated_at" IS 'Waktu diperbarui';

COMMENT ON TABLE "order_items" IS 'Detail item transaksi; dapat item satuan atau item hasil bundling';

COMMENT ON COLUMN "order_items"."id" IS 'Primary key order item';

COMMENT ON COLUMN "order_items"."uuid" IS 'ID publik order item';

COMMENT ON COLUMN "order_items"."order_id" IS 'FK ke orders.id';

COMMENT ON COLUMN "order_items"."item_type" IS 'Jenis item: location/crew/rental/food_and_beverage/expendable';

COMMENT ON COLUMN "order_items"."item_id" IS 'ID item sesuai item_type';

COMMENT ON COLUMN "order_items"."item_name_snapshot" IS 'Nama item saat checkout';

COMMENT ON COLUMN "order_items"."quantity" IS 'Jumlah item';

COMMENT ON COLUMN "order_items"."unit_price_snapshot" IS 'Harga per unit saat checkout';

COMMENT ON COLUMN "order_items"."line_total" IS 'Total baris = unit_price_snapshot * quantity';

COMMENT ON COLUMN "order_items"."is_from_bundle" IS 'Penanda item berasal dari bundle';

COMMENT ON COLUMN "order_items"."bundle_id" IS 'FK ke bundles.id jika dari bundling';

COMMENT ON COLUMN "order_items"."booking_start" IS 'Mulai booking; khusus item yang butuh waktu';

COMMENT ON COLUMN "order_items"."booking_end" IS 'Selesai booking; khusus item yang butuh waktu';

COMMENT ON COLUMN "order_items"."created_at" IS 'Waktu dibuat';

COMMENT ON COLUMN "order_items"."updated_at" IS 'Waktu diperbarui';

COMMENT ON TABLE "crew_images" IS 'Gambar untuk crew';

COMMENT ON COLUMN "crew_images"."id" IS 'Primary key gambar';

COMMENT ON COLUMN "crew_images"."crew_id" IS 'FK ke crews.id';

COMMENT ON COLUMN "crew_images"."url" IS 'URL gambar';

COMMENT ON COLUMN "crew_images"."position" IS 'Urutan gambar';

COMMENT ON TABLE "expendable_images" IS 'Gambar untuk expendables';

COMMENT ON COLUMN "expendable_images"."id" IS 'Primary key gambar';

COMMENT ON COLUMN "expendable_images"."expendable_id" IS 'FK ke expendables.id';

COMMENT ON COLUMN "expendable_images"."url" IS 'URL gambar';

COMMENT ON COLUMN "expendable_images"."position" IS 'Urutan gambar';

COMMENT ON TABLE "food_and_beverage_images" IS 'Gambar untuk food_and_beverage';

COMMENT ON COLUMN "food_and_beverage_images"."id" IS 'Primary key gambar';

COMMENT ON COLUMN "food_and_beverage_images"."food_and_beverage_id" IS 'FK ke food_and_beverage.id';

COMMENT ON COLUMN "food_and_beverage_images"."url" IS 'URL gambar';

COMMENT ON COLUMN "food_and_beverage_images"."position" IS 'Urutan gambar';

COMMENT ON TABLE "rental_images" IS 'Gambar untuk rentals';

COMMENT ON COLUMN "rental_images"."id" IS 'Primary key gambar';

COMMENT ON COLUMN "rental_images"."rental_id" IS 'FK ke rentals.id';

COMMENT ON COLUMN "rental_images"."url" IS 'URL gambar';

COMMENT ON COLUMN "rental_images"."position" IS 'Urutan gambar';

COMMENT ON COLUMN "location_item_category"."location_id" IS 'FK ke locations.id';

COMMENT ON COLUMN "location_item_category"."item_category_id" IS 'FK ke item_categories.id';

COMMENT ON COLUMN "rental_item_category"."rental_id" IS 'FK ke rentals.id';

COMMENT ON COLUMN "rental_item_category"."item_category_id" IS 'FK ke item_categories.id';

COMMENT ON COLUMN "expendable_item_category"."expendable_id" IS 'FK ke expendables.id';

COMMENT ON COLUMN "expendable_item_category"."item_category_id" IS 'FK ke item_categories.id';

COMMENT ON COLUMN "food_and_beverage_item_category"."food_and_beverage_id" IS 'FK ke food_and_beverage.id';

COMMENT ON COLUMN "food_and_beverage_item_category"."item_category_id" IS 'FK ke item_categories.id';

COMMENT ON COLUMN "crew_item_category"."crew_id" IS 'FK ke crews.id';

COMMENT ON COLUMN "crew_item_category"."item_category_id" IS 'FK ke item_categories.id';

COMMENT ON COLUMN "location_item_sub_category"."location_id" IS 'FK ke locations.id';

COMMENT ON COLUMN "location_item_sub_category"."item_sub_category_id" IS 'FK ke item_sub_categories.id';

COMMENT ON COLUMN "rental_item_sub_category"."rental_id" IS 'FK ke rentals.id';

COMMENT ON COLUMN "rental_item_sub_category"."item_sub_category_id" IS 'FK ke item_sub_categories.id';

COMMENT ON COLUMN "expendable_item_sub_category"."expendable_id" IS 'FK ke expendables.id';

COMMENT ON COLUMN "expendable_item_sub_category"."item_sub_category_id" IS 'FK ke item_sub_categories.id';

COMMENT ON COLUMN "food_and_beverage_item_sub_category"."food_and_beverage_id" IS 'FK ke food_and_beverage.id';

COMMENT ON COLUMN "food_and_beverage_item_sub_category"."item_sub_category_id" IS 'FK ke item_sub_categories.id';

COMMENT ON COLUMN "crew_item_sub_category"."crew_id" IS 'FK ke crews.id';

COMMENT ON COLUMN "crew_item_sub_category"."item_sub_category_id" IS 'FK ke item_sub_categories.id';

COMMENT ON COLUMN "bundle_bundle_types"."bundle_id" IS 'FK ke bundles.id';

COMMENT ON COLUMN "bundle_bundle_types"."bundle_type_id" IS 'FK ke bundle_types.id';

COMMENT ON COLUMN "bundle_bundle_categories"."bundle_id" IS 'FK ke bundles.id';

COMMENT ON COLUMN "bundle_bundle_categories"."bundle_category_id" IS 'FK ke bundle_categories.id';

ALTER TABLE "location_embeddings" ADD FOREIGN KEY ("location_id") REFERENCES "locations" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "location_tag" ADD FOREIGN KEY ("location_tag_id") REFERENCES "location_tags" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "location_tag" ADD FOREIGN KEY ("location_id") REFERENCES "locations" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "location_images" ADD FOREIGN KEY ("location_id") REFERENCES "locations" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "expendable_images" ADD FOREIGN KEY ("expendable_id") REFERENCES "expendables" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "rental_images" ADD FOREIGN KEY ("rental_id") REFERENCES "rentals" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "food_and_beverage_images" ADD FOREIGN KEY ("food_and_beverage_id") REFERENCES "food_and_beverage" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "crew_skills" ADD FOREIGN KEY ("crew_id") REFERENCES "crews" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "crew_images" ADD FOREIGN KEY ("crew_id") REFERENCES "crews" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "bundle_crews" ADD FOREIGN KEY ("bundle_id") REFERENCES "bundles" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "bundle_crews" ADD FOREIGN KEY ("crew_id") REFERENCES "crews" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "bundle_food_and_beverages" ADD FOREIGN KEY ("bundle_id") REFERENCES "bundles" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "bundle_food_and_beverages" ADD FOREIGN KEY ("food_and_beverage_id") REFERENCES "food_and_beverage" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "bundle_expendables" ADD FOREIGN KEY ("bundle_id") REFERENCES "bundles" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "bundle_expendables" ADD FOREIGN KEY ("expendable_id") REFERENCES "expendables" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "bundle_rentals" ADD FOREIGN KEY ("bundle_id") REFERENCES "bundles" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "bundle_rentals" ADD FOREIGN KEY ("rental_id") REFERENCES "rentals" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "food_and_beverage_tag" ADD FOREIGN KEY ("food_and_beverage_tag_id") REFERENCES "food_and_beverage_tags" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "food_and_beverage_tag" ADD FOREIGN KEY ("food_and_beverage_id") REFERENCES "food_and_beverage" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "orders" ADD FOREIGN KEY ("user_uuid") REFERENCES "profiles" ("user_uuid") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "orders" ADD FOREIGN KEY ("promo_code_id") REFERENCES "promo_codes" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "order_items" ADD FOREIGN KEY ("order_id") REFERENCES "orders" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "order_items" ADD FOREIGN KEY ("bundle_id") REFERENCES "bundles" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "location_reviews" ADD FOREIGN KEY ("user_uuid") REFERENCES "profiles" ("user_uuid") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "location_reviews" ADD FOREIGN KEY ("location_id") REFERENCES "locations" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "location_reviews" ADD FOREIGN KEY ("order_id") REFERENCES "orders" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "location_item_category" ADD FOREIGN KEY ("location_id") REFERENCES "locations" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "location_item_category" ADD FOREIGN KEY ("item_category_id") REFERENCES "item_categories" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "rental_item_category" ADD FOREIGN KEY ("rental_id") REFERENCES "rentals" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "rental_item_category" ADD FOREIGN KEY ("item_category_id") REFERENCES "item_categories" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "expendable_item_category" ADD FOREIGN KEY ("expendable_id") REFERENCES "expendables" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "expendable_item_category" ADD FOREIGN KEY ("item_category_id") REFERENCES "item_categories" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "food_and_beverage_item_category" ADD FOREIGN KEY ("food_and_beverage_id") REFERENCES "food_and_beverage" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "food_and_beverage_item_category" ADD FOREIGN KEY ("item_category_id") REFERENCES "item_categories" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "crew_item_category" ADD FOREIGN KEY ("crew_id") REFERENCES "crews" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "crew_item_category" ADD FOREIGN KEY ("item_category_id") REFERENCES "item_categories" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "location_item_sub_category" ADD FOREIGN KEY ("location_id") REFERENCES "locations" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "location_item_sub_category" ADD FOREIGN KEY ("item_sub_category_id") REFERENCES "item_sub_categories" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "rental_item_sub_category" ADD FOREIGN KEY ("rental_id") REFERENCES "rentals" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "rental_item_sub_category" ADD FOREIGN KEY ("item_sub_category_id") REFERENCES "item_sub_categories" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "expendable_item_sub_category" ADD FOREIGN KEY ("expendable_id") REFERENCES "expendables" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "expendable_item_sub_category" ADD FOREIGN KEY ("item_sub_category_id") REFERENCES "item_sub_categories" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "food_and_beverage_item_sub_category" ADD FOREIGN KEY ("food_and_beverage_id") REFERENCES "food_and_beverage" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "food_and_beverage_item_sub_category" ADD FOREIGN KEY ("item_sub_category_id") REFERENCES "item_sub_categories" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "crew_item_sub_category" ADD FOREIGN KEY ("crew_id") REFERENCES "crews" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "crew_item_sub_category" ADD FOREIGN KEY ("item_sub_category_id") REFERENCES "item_sub_categories" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "bundle_bundle_types" ADD FOREIGN KEY ("bundle_id") REFERENCES "bundles" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "bundle_bundle_types" ADD FOREIGN KEY ("bundle_type_id") REFERENCES "bundle_types" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "bundle_bundle_categories" ADD FOREIGN KEY ("bundle_id") REFERENCES "bundles" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "bundle_bundle_categories" ADD FOREIGN KEY ("bundle_category_id") REFERENCES "bundle_categories" ("id") DEFERRABLE INITIALLY IMMEDIATE;
