import type { SupabaseClient } from "@supabase/supabase-js";

import { seedMasterTable, type SeederRow } from "./_shared";

const itemSubCategoriesDummyRows: SeederRow[] = [
  { name: "Handy Talky", short_code: "HT" },
  { name: "Solidcom", short_code: "SC" },
  { name: "Snacks", short_code: "SN" },
  { name: "Beverages", short_code: "BV" },
  { name: "Paket Catering", short_code: "PC" },
  { name: "P3K Package", short_code: "PP" },
  { name: "Meja", short_code: "MJ" },
  { name: "Kursi", short_code: "KS" },
  { name: "Tenda", short_code: "TD" },
  { name: "Table Cover", short_code: "TC" },
  { name: "Lampu", short_code: "LP" },
  { name: "Kipas Angin", short_code: "KA" },
  { name: "Cooler Box", short_code: "CB" },
  { name: "Water Boiler", short_code: "WB" },
  { name: "Water Tank Jug", short_code: "WJ" },
  { name: "Termos Pemanas Air", short_code: "TP" },
  { name: "Dispenser Galon", short_code: "DG" },
  { name: "Nespresso Coffee Machine Capsule", short_code: "NP" },
  { name: "Rice/Ice Bucket", short_code: "RB" },
  { name: "Troli Barang", short_code: "TB" },
  { name: "Kabel Roll", short_code: "KR" },
  { name: "Kabel Terminal", short_code: "KT" },
  { name: "Panel Box + Power Cable", short_code: "PB" },
  { name: "Genset", short_code: "GS" },
  { name: "Tangki/Jerigen", short_code: "TK" },
  { name: "Ground Cable Protectors", short_code: "GC" },
  { name: "Safety Traffic Cone", short_code: "ST" },
  { name: "Traffic Light", short_code: "TL" },
  { name: "Toa Megaphone", short_code: "TM" },
  { name: "Smoke Gun / Fog Machine", short_code: "SG" },
  { name: "Speaker Bluetooth", short_code: "SB" },
  { name: "Black Tape", short_code: "BT" },
  { name: "Masking Tape", short_code: "MT" },
  { name: "Plastik Ikan", short_code: "PI" },
  { name: "Cling Wrap", short_code: "CW" },
  { name: "Binder Clips", short_code: "BC" },
  { name: "Kertas Karton", short_code: "KK" },
  { name: "Pelindung Sepatu", short_code: "PS" },
  { name: "DuRent Crew", short_code: "0001" },
  { name: "Hosea", short_code: "0002" },
  { name: "Marco", short_code: "0003" },
  { name: "Pickup Truck", short_code: "PT" },
  { name: "Bye Bye Fever", short_code: "BF" },
  { name: "Plastik Sampah", short_code: "PL" },
  { name: "Gelas", short_code: "GL" },
  { name: "Sendok", short_code: "SD" },
  { name: "Jas Hujan", short_code: "JH" },
  { name: "Terpal", short_code: "TR" },
  { name: "Transparent tape", short_code: "TT" },
  { name: "Anti slip tape", short_code: "AT" },
  { name: "Kawat bendrat", short_code: "KB" },
  { name: "Baterai", short_code: "BA" },
  { name: "Shooting Package", short_code: "SP" },
];

export async function seedItemSubCategories(supabase: SupabaseClient) {
  return seedMasterTable(
    supabase,
    "item_sub_categories",
    itemSubCategoriesDummyRows,
  );
}
